# PostgreSQL Database Configuration
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name}
brevo.api.key=${brevo.api.key}
brevo.sender.email=no-reply@niadesk.com
brevo.sender.name=${BREVO_SENDER_NAME:QuoteApp}
# JPA/Hibernate Configuration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# PostgreSQL specific
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jackson.serialization.fail-on-empty-beans=false
